syntax = "proto3";
package clipx;

message Hello {
    uint32 proto_version = 1;
}

message ClipboardMessage {
    oneof content {
        string text = 1;
    }
}

message Announce {
  string device_id = 1;
  string device_name = 2;
  DeviceType device_type = 3;
  uint32 ws_port = 4;
  bytes public_key = 5;
}

enum DeviceType {
  WINDOWS = 0;
  ANDROID = 1;
  LINUX = 2;
  MACOS = 3;
}

message Challenge {
  string request_id = 1;
  bytes nonce = 2;
}

message ChallengeResponse {
  string request_id = 1;
  bytes signature = 2;
}

message UdpEnvelope {
  oneof payload {
    Announce announce = 1;
    Challenge challenge = 2;
    ChallengeResponse challenge_response = 3;
  }
}